version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine  
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt/live/choomba.formuls.xyz:/etc/letsencrypt/live/choomba.formuls.xyz' 
      - '/etc/letsencrypt/archive/choomba.formuls.xyz:/etc/letsencrypt/archive/choomba.formuls.xyz'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db_data:/choomba/backend  # Используем том для хранения базы данных
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - dev

volumes:
  db_data:  # Определяем том для базы данных
